import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import fetch from "isomorphic-unfetch";
import Jumbotron from "../components/Jumbotron"
import Link from "next/link";
const Home = ({ notes }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Jumbotron />
      <div className="container-fluid mb-5">
        <div className="row">
          {
            notes.map(note => {
              return (

                <div key={note._id} className="col-sm-6 mb-2">

                    <div className="card">
                      <div className="card-body">
                        <h5 className="card-title">{note.title}</h5>
                        <i className="text-secondary">{note.origin}</i> <br />
                      <p className="card-text text-wrap">{note.Description.slice(0, 30)}...<Link href={`/${note._id}`}><a className="text-primary">Read More</a></Link></p>
                      
                      </div>
                  </div>
                </div>
              )
            })
          }
        </div>

      </div>
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch(`http://localhost:3000/api/notes`);
  const { data } = await res.json();
  return { notes: data }
}

export default Home;
